### ISSUE TITLE
Does Not work with FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by programmerneo** [bhollis/jsonview#101]
I used this all the time with Standard Firefox, I switched to FirefoxDeveloperEdition, and this plugin does not work

**Comment by Curdal** [comment]
@programmerneo I've been using Firefox Dev for a while now and this extension worked fine until a recent update.
But yes there seems to be a bug somewhere now

**Comment by bhollis** [comment]
I wonder if Firefox Dev is a different product code. Could you elaborate on what "does not work" means? Does it not show up as an extension at all?

**Comment by bhollis** [comment]
Or it might be that e10s is turned on in Firefox Dev... which I just merged support for!

**Comment by programmerneo** [comment]
It does not "json pretty", the responses, it is now plain text, 
It Did used to work for FF Developer. Stopped working.

**Comment by wavded** [comment]
I also can confirm it not working in Firefox Dev Browser when I have multi-process enabled.  Works when disabled.

**Comment by bhollis** [comment]
OK. I just installed FirefoxDeveloperEdition and it works fine. It would not work with multi-process enabled because the version of JSONView that is released (0.9) does not work with multi-process.

Resolving as a duplicate of #97.

**Comment by Curdal** [comment]
Okay it seems I had multi-process enabled. So it works fine when I disable it.
Thanks

**Comment by bhollis** [comment]
The new 1.0.2 version supports multi-process.
