### ISSUE TITLE
Latest version breaks JSON View

### ISSUE THREAD

**Issue by alquemedia** [bhollis/jsonview#102]
The version released 31.05.15 has broken JSONView, it is no longer working for any URLs that output as type application/json.

Noted for Firefox 35.0.1 (Ubuntu)

Was previously working until this version

**Comment by bhollis** [comment]
Could you provide an example of a non-working URL? This one works for me: http://jsonview.com/example.json

**Comment by bhollis** [comment]
Unbelievably, Mozilla changed their tools without warning to produce extensions that would silently fail to work on Firefox older than version 38: https://github.com/mozilla/jpm/issues/261

Upgrading to the latest Firefox will make JSONView work again. Or, do like I did and switch to Chrome.

**Comment by bhollis** [comment]
(And I've changed the compatibility values on AMO so hopefully this won't hit too many people from now on).
