### ISSUE TITLE
jsonview not parsing data

### ISSUE THREAD

**Issue by dukejib** [bhollis/jsonview#103]
Firefox 38.0
Ubuntu 15.04 

Jsonview is unable to render json properly. It shows as single line.

**Comment by bhollis** [comment]
You'll have to give me a little more to go on for me to figure out the problem you're having. :wink: 

What's the URL you're having trouble with? What happens when you visit http://jsonview.com/example.json ?

**Comment by dukejib** [comment]
Hi. sorry for late reply. 
I tried to open the given link, but it came out unparsed. However, i removed the extension. and restarted the system. Reinstalled the addon and its working fine. 
Thanks for your time and reply and for a great addon.

**Comment by dukejib** [comment]
Weird. It stated to show plain text again. 
like this.

{"hey": "guy","anumber": 243,"anobject": {"whoa": "nuts","anarray": [1,2,"thr<h1>ee"], "more":"stuff"},"awesome": true,"bogus": false,"meaning": null, "japanese":"明日がある。", "link": "http://jsonview.com", "notLink": "http://jsonview.com is great"}

**Comment by bhollis** [comment]
Hmm, sounds like a problem where the extension is not staying enabled. When you go to `about:addons` does it show up as enabled?

**Comment by dukejib** [comment]
yes it is enabled.  The Default is checked. So i tried  "on" as well. but it remains same.
