### ISSUE TITLE
Large file being truncated

### ISSUE THREAD

**Issue by gricey432** [bhollis/jsonview#104]
A large JSON file, e.g.
http://storage.googleapis.com/cdn.steam.tools/data/set_data.json
Loads completely with JSONView disabled however with it enabled it only loads part of the file and then says "There was an error parsing the JSON document. The document may not be well-formed."
JSONView 1.0.4
Firefox 38.0.5

**Comment by gricey432** [comment]
I believe this is the same issue as #54 however it says this appeared to be fixed

**Comment by bhollis** [comment]
I'm afraid I can't reproduce that problem - it loads fine on Firefox 30 on OS X for me.

**Comment by Elusive138** [comment]
Connection speed might play a part. @gricey432's example works for me, but this one fails: http://api.highcharts.com/highcharts/option/dump.json

Tried with JSONView 1.0.2 in both FF 39.0.3 and 41.0a2 2015-08-08, with wildly varying lengths on each load (from ~20000 to ~2000000). It did work once out of several attempts.

**Comment by justinhuntgc** [comment]
I'm also experiencing this issue on a slow loading document, it seems to truncate at between 4500-25000 lines, although occasionally it will work.  My work around is to use chrome and "JSON Formatter" extension.

Currently on Firefox v41 and JSONView 1.0.2.

**Comment by bhollis** [comment]
I don't doubt that this is a real issue, but I'm not sure how to reproduce it, or go about fixing it.

My hunch is that it's in the odd `nsIStreamListener` callbacks: https://github.com/bhollis/jsonview/blob/master/lib/jsonview.js#L47

I remember having to make a bunch of crazy workarounds for old issues that may or may not still exist. If somebody wants to, they can tweak this, try to fix it, and if it works, submit a PR.

**Comment by Elusive138** [comment]
For reproduction, I'd suggest going through a throttling webproxy (Fiddler might help).

I might take a look if time permits.

**Comment by gricey432** [comment]
This seems to be fixed for me now

**Comment by cardoe** [comment]
I can reproduce this with a 430kb JSON file that I can provide (unfortunately I don't have permissions to attach it to the ticket). I'm opening it via file:///. You will have to tell JSONView to handle text/plain via preferences.

**Comment by dgem** [comment]
I'm also seeing this error on some APIs I'm working on... Is it dependent on content length being set correctly ?

**Comment by bhollis** [comment]
I don't know how to reliably reproduce it. Regardless, I'm not convinced this is a problem with JSONView. Rather, I believe it is a problem with the Firefox APIs that JSONView has to use (`nsIStreamListener` and `nsIStreamConverter`). If I could get a solid reproduction of the bug (like I have with some other problems which turned out to be Firefox API weirdness), I'd be happy to hammer on it until I found a fix, but I haven't, so I don't really have much to go on. If you'd like, you can switch to Chrome as I have, which seems to have fewer mystery bugs.

**Comment by Elusive138** [comment]
Firefox now has its own built-in JSON viewer: https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer

So I guess fixing this extension isn't really important.

Incidentally, the built-in viewer seems to suffer from the same bug (though I'm having trouble reproducing reliably). If that's the case, then it would be good to report to Mozilla.

**Comment by gricey432** [comment]
I'm still convinced it's a timeout sort of issue, I seem to get it on large files during peak times when my internet is slow (100-200 kBps) but at work during the day the same file has no issues (5MBps).
If you have a decent connection speed, it could be hard to reproduce.

**Comment by bhollis** [comment]
Maybe there's an event we aren't listening to?

**Comment by cardoe** [comment]
@gricey432 As noted above, the issue happens with file:/// URLs so it does not have anything to do with connection speed.

**Comment by gricey432** [comment]
@cardoe good point, I'm back to square one understanding this then.
We'll have to keep an eye on the official json viewer in Firefox that @Elusive138 mentioned and see if someone brings up the issue there / they fix it in theirs.
