### ISSUE TITLE
The url can't formatter on firefox 39.0

### ISSUE THREAD

**Issue by srwu** [bhollis/jsonview#106]
http://portal.m.jd.com/client.action?functionId=welcomeHome&body={%22geo%22:{%22lng%22:%220.000000%22,%22lat%22:%220.000000%22},%22identity%22:%224d40ec0d2b05456d106115e2ac54395c35692d72%22}&d_model=x86_64&networkType=wifi&adid=A0F280D3-C9C1-4227-A612-E3DE6E6C60E3&osVersion=8.4&d_brand=apple&client=apple&screen=750*1334&area=2_78_79_0&build=23164&uuid=SR5nCoavKFxOVKiA5F0XPw==&clientVersion=4.3.0&openudid=4d40ec0d2b05456d106115e2ac54395c35692d72&partner=apple&st=1437015515869&sign=TEqZKN3DVOU_UdVTJyqOSg&sv=1

**Comment by auscompgeek** [comment]
https://github.com/bhollis/jsonview#common-issues

Also, please write coherent sentences in future...

**Comment by bhollis** [comment]
Let's be nice!

@srwu, the problem is that the JSON is being served as `text/plain`, so it's being displayed as plain text.
