### ISSUE TITLE
Render output as PNG or SVG

### ISSUE THREAD

**Issue by tonypiazza** [bhollis/jsonview#113]
Would you consider adding an option to render the output as PNG or SVG? Let me know your thoughts on this. Thanks for your work on this. It's been very useful.

**Comment by bhollis** [comment]
Hi, would you mind elaborating on what you'd use this for?

**Comment by tonypiazza** [comment]
I would use the generated images in the software development training courses I am writing. As you know, JSON is an important format that touches both front-end and back-end tools and systems. For people who are new to JSON, I find it particularly helpful to use visualizations like those produced by tools such as JSONView. For most of my courses, clients distribute them in PDF format. So having an image would make it possible to embed them. Let me know if you need any more info. Thanks!

**Comment by bhollis** [comment]
I think the best way to do it would be to take a screenshot and put that in your PDF.

**Comment by tonypiazza** [comment]
I've done that but many of my JSON files are too long (more than I can fit on the screen) for that. It would be much easier and more precise to have the option to generate an image directly in the browser that I can just copy and paste into my material. Thanks anyway for considering it.

**Comment by nqv** [comment]
@tonypiazza I find Nimbus Screenshot addon is very easy to use and it can take screenshot of entire page.
