### ISSUE TITLE
No JSON formatting with current Nightly

### ISSUE THREAD

**Issue by djc** [bhollis/jsonview#115]
With current Firefox Nightly (44.0a1, 2015-10-18), I don't see the JSON being formatted; it just renders as text. This can be reproduced with http://jsonview.com/example.json, for example.

I don't see any messages in the Brower Console.

**Comment by bhollis** [comment]
Verified. Looks like they've once again changed something that breaks JSONView. That said, I'll probably not bother with it for a while - sometimes the Nightly breaks things, and they fix it later.

**Comment by bhollis** [comment]
I rebuilt the extension with a newer version of `jpm` and now it works. 1.1.0 has been submitted to AMO.

**Comment by djc** [comment]
Thanks!
