### ISSUE TITLE
Doesn't work with long numbers

### ISSUE THREAD

**Issue by bhavinmdesai** [bhollis/jsonview#116]
The plugin prints 381111320260379700 for actual value 381111320260379738.

**Comment by jerone** [comment]
See https://github.com/bhollis/jsonview#common-issues with explanation here: https://github.com/bhollis/jsonview/issues/21#issuecomment-7027041

**Comment by stormlily13** [comment]
Two men

2015-10-19 10:32 GMT-07:00, Jeroen van Warmerdam <notifications@github.com>:

**Comment by stormlily13** [comment]
Hjb

**Comment by stormlily13** [comment]
What do i do

**Comment by bhollis** [comment]
If you want to use that JSON from JavaScript, you need smaller numbers, or to represent them as strings. If your language interprets JSON numbers differently, you need to wait for the next version of JSONView that can display them correctly. 

-Ben

**Comment by bhavinmdesai** [comment]
Thanks. I would like to wait for the next version. I have observed one
thing is this is a bug for all the Firefox extensions which formats JSON.
On chrome, it works fine.
