### ISSUE TITLE
Support mime type wild cards

### ISSUE THREAD

**Issue by mheinzerling** [bhollis/jsonview#117]
We are working with custom mime types like application/vnd.XYZ-v1+json, so adding a wild card mime type like application/*+json would be awesome.

**Comment by bhollis** [comment]
Unfortunately I don't think Firefox allows this, but I'll look into it.

**Comment by DidierLoiseau** [comment]
+1, it would be an interesting feature indeed. The Chrome port seems to detect JSON without this configuration parameter though.

**Comment by bhollis** [comment]
The chrome extension works quite differently.

**Comment by mhohai** [comment]
Content-Type: "text/html;

but I want see it as json, and it's json.
can add quick function to do it?

**Comment by bhollis** [comment]
Nope
