### ISSUE TITLE
JSONView 1.1.0 & Firefox Developer 44.0a2

### ISSUE THREAD

**Issue by JamoCA** [bhollis/jsonview#119]
Firefox Developer no longer displays "application/json" data to the screen.  It suppresses the output to the browser and only displays the response within the F12 developer tools.  It doesn't matter whether JSONView is enabled or not... no content is displayed within the browser.

As a result, will this addon be able to override and "View JSON documents in the browser" or will this function only be available via the developer tools?

**Comment by Cordazar** [comment]
I'm running the same setup with JSONView 1.1.0 and FF Dev 44.0a2 and haven't experienced any problems with the viewing of json output.

**Comment by JamoCA** [comment]
Sorry... after disabling all addons, reevaluating, refreshing the browser and resinstalling all addons, I finally determined it was all due to the NoScript addon.  It also appears that Firefox Developer has its own new JSON renderer... so JSONView may not be needed in the future.
![ffdev_json](https://cloud.githubusercontent.com/assets/1112671/11152613/7bfa941e-89e8-11e5-9c4b-6bdab39d0129.png)

**Comment by choma** [comment]
I can confirm the issue when noscript is enabled. It seems to break the dev edition json viewer too, as reported [here](https://forums.informaction.com/viewtopic.php?f=10&t=21399&hilit=json).

**Comment by bhollis** [comment]
Yes, JSONView uses JavaScript so you'll need it to be on.
