### ISSUE TITLE
handle multiple json objects in a file

### ISSUE THREAD

**Issue by davidelang** [bhollis/jsonview#122]
if you have a file with multiple json objects
{json}
{json}
{json}
etc

jsonview will refuse to do anythng with the file, add a , to the end of every line and wrap it with [] and it works.

**Comment by bhollis** [comment]
Unfortunately, according to spec, a file with multiple JSON objects in it
is not JSON. JSONView only views valid JSON.

**Comment by davidelang** [comment]
Ok, if you think it's better to stick with the letter of the spec rather than what people do in the real world, I'll delete this and look for something that can work in the real world.
