### ISSUE TITLE
Scheme-less URI not clickable

### ISSUE THREAD

**Issue by toddb** [bhollis/jsonview#124]
Great work with JSONView thanks. 

I am finding in both Chrome and Firefox that string that are scheme-less URI are not clickable and I would them to be so.

For example: `//someapp.herokuapp.com/task/1l9fz7bhahh` should be equivalent to `https://someapp.herokuapp.com/task/1l9fz7bhahh` (given I came in on `https`)

This is a valid URI syntax as per [RFC 3986: Section 4.2](https://tools.ietf.org/html/rfc3986#section-4.2)

Note: I note #118 might interact with this if you were running locally but seems orthogonal

### References for clarification:

- http://stackoverflow.com/questions/4831741/can-i-change-all-my-http-links-to-just

**Comment by bhollis** [comment]
Hi @toddb, thanks for taking the time to submit a feature request. Unfortunately, I'm not really comfortable extending the regex for URLs. For example, this string could also be an XPath expression or something else - I'm only going to auto-linkify things that are unambigiously URLs. See #82 for more discussion on this.

Note that I do not maintain the Chrome extension, so you may be able to persuade them to do differently.
