### ISSUE TITLE
Any reason why KEY is not represented in string format as JSON standard?

### ISSUE THREAD

**Issue by darshand** [bhollis/jsonview#126]
According to `JSON` standards, `key` should be in string format. Because, if used without string quotes it might end up with matching any `keyword` in parsing language and cause syntax error.
While `jsonview` beautifies the `json` data in good way, but in the same time I feel it is not following standards as specified by `json`. 

All the beautified `json` data from `jsonview` fails in `json` validator. Any specific reason for not showing key in string format?

**Comment by bhollis** [comment]
I'm not sure I understand. JSONView is formatting JSON for human readability. But if you copy/paste the JSON, it is still valid JSON (with quotes and everything).
