### ISSUE TITLE
Replace ellipses with number of items that can be expanded.

### ISSUE THREAD

**Issue by lawrencechernin** [bhollis/jsonview#128]
for example
change:
- {...},

to
- {6},

**Comment by bhollis** [comment]
That's an interesting idea. I'll try it out and see if it's confusing.

**Comment by bhollis** [comment]
I'm doing this with CSS, so it's hard to do the count.

**Comment by stanio** [comment]
I think it would be better to inline all child items, possibly grayed out, cutting off to a single (the first) line, possibly using `text-overflow: ellipsis` to indicate there's more to show.  This style I've seen with few other apps including the new built-in Firefox JSON viewer (which I don't like as I like JSONView).  I'll try to prepare the styles for demonstration.

**Comment by stanio** [comment]
Haven't had the time to look into implementing this into a PR but here's what I mean:

-   _Option 1: Inline all of the object/array content, and display ellipsis on overflow_

    ![jsonview-inline-1](https://cloud.githubusercontent.com/assets/1247730/17839964/d8225252-6801-11e6-8147-4e939d94500c.png)

-  _Option 2: Same as Option 1 but always collapse nested object/array into ellipsis_

    ![jsonview-inline-2](https://cloud.githubusercontent.com/assets/1247730/17839971/fdc4a528-6801-11e6-9f91-bca385d3bce3.png)

    Collapsing the view further:

    ![jsonview-inline-3](https://cloud.githubusercontent.com/assets/1247730/17839977/0b27b480-6802-11e6-9bf2-66bd768982bd.png)

-  If the view is wide enough whole of the collapsed object/array is visible on one line:

    ![jsonview-inline-4](https://cloud.githubusercontent.com/assets/1247730/17839984/25950c50-6802-11e6-8d2b-44fdd8f33267.png)

    ![jsonview-inline-5](https://cloud.githubusercontent.com/assets/1247730/17839985/2adb1d94-6802-11e6-9742-31057955a1cc.png)

To implement this I'll need to add `class="collapsed"` to parent `LI` elements encapsulating the property name and the object/array value, and then add few CSS rules involving `display: flex`, and `text-overflow: ellipsis` as mentioned before.

**Comment by bhollis** [comment]
I like that! Would you be able to send a PR for it?

The only thing to keep in mind is that copy-paste should preserve valid JSON.

**Comment by bhollis** [comment]
This is related to #131.

**Comment by stanio** [comment]
@bhollis:

> I like that! Would you be able to send a PR for it?
> 
> The only thing to keep in mind is that copy-paste should preserve valid JSON.

I'm able to prepare a PR for it, now that I have some free time on my hands, but I've played with it a bit more, and realized the original formatting could not be kept as currently is as the collapsed nested content would be forced inline.  If that's not absolute showstopper(?) I will go ahead and prepare a PR for this.  May be we could have this behavior behind a preference?

**Comment by bhollis** [comment]
Thanks for taking a look! I'll see if I can get some free time this weekend to go over what you're proposing. 

-Ben
