### ISSUE TITLE
Add option for filesize limit

### ISSUE THREAD

**Issue by ttsirkia** [bhollis/jsonview#130]
If the JSON file is very big (ie. http://rata.digitraffic.fi/api/v1/live-trains Finnish live train data), it takes forever to render the file.

It would be handy to add an option that display JSON without any formatting if the filesize is above some (maybe user-defined) limit.

**Comment by EmilStenstrom** [comment]
I've had several browser hangs because JSONView tried to load huge files. I really would like an option like @ttsirkia suggests above.

**Comment by bhollis** [comment]
Looks like #111 make JSONView way slower, and that's why it takes so long. I'll try to optimize.
