### ISSUE TITLE
Add JSON array counter

### ISSUE THREAD

**Issue by djouuuuh** [bhollis/jsonview#131]
Hi @bhollis,

Nice add-on!

What do you think of adding a little label with the JSON array count ? Thanks in advance!

![label](https://cloud.githubusercontent.com/assets/5645371/15833022/0351fa68-2c25-11e6-91d4-4c99e374e491.png)

**Comment by havanagrawal** [comment]
I'd like to work on this please, if possible. Should I start work and make a PR for this? @bhollis

**Comment by djouuuuh** [comment]
@havanagrawal I already forked and add the feature. But since @bhollis doesn't reply, I didn't make a PR... If you want to see the counter: https://github.com/djouuuuh/jsonview/commits/master

**Comment by bhollis** [comment]
Sorry, I've been traveling. I like the idea, as long as we make sure it doesn't interfere with copy/paste. Please send a PR!

**Comment by djouuuuh** [comment]
@bhollis It is currently interfering with copy/paste! How to avoid this ? :worried:

**Comment by bhollis** [comment]
It's tricky! I usually have to do tricks with CSS user-select property.

**Comment by danitome24** [comment]
How is this feature going? Is it going to be added? I think it's very useful.

**Comment by bhollis** [comment]
I went ahead and implemented this without interfering with copy/paste (building on @djouuuuh's code!) but I haven't been able to get it to not affect the copy-paste output - it causes there to be unnecessary newlines and indentation problems. I've parked this in the `array-counter` branch if anyone wants to pick it up and keep working on it.

**Comment by RaXaR** [comment]
Hi :) this feature is also something I'd like to see implemented.
I found this tidbit that makes some texts unselectable via CSS.
```
.unselectable {
  -webkit-user-select: none;  /* Chrome all / Safari all */
  -moz-user-select: none;     /* Firefox all */
  -ms-user-select: none;      /* IE 10+ */
  user-select: none;          /* Likely future */       
}
```
Source: https://css-tricks.com/copy-paste-the-web/#article-header-id-3

Hope this helps :)
