### ISSUE TITLE
Avoiding sorting objects

### ISSUE THREAD

**Issue by netBytesSoftware** [bhollis/jsonview#133]
If I have this JSON file content:

> {
> 	"2016": ["aaa", "bbb", "ccc"],
> 	"2015": ["ddd", "eee"],
> 	"2014": ["fff", "ggg", "hhh", "iii"]
> }

JSONView shows:

> {
>     "2014": [
>         "fff",
>         "ggg",
>         "hhh",
>         "iii"
>     ],
>     "2015": [
>         "ddd",
>         "eee"
>     ],
>     "2016": [
>         "aaa",
>         "bbb",
>         "ccc"
>     ]
> }

Is it possible not to sort objects which name is a number? If I use that JSON information in a loop to display it I get 2016, 2015 and 2014 instead of 2014, 2015 and 2016. It is misleading. 
Perhaps JSONView could have a checkbox parameter to enable/disable sorting.

Thanks.

**Comment by bhollis** [comment]
The order of keys in a JSON object is not specified. In our case, we're
just printing in whichever order the Firefox JSON implementation returns
them in.

**Comment by netBytesSoftware** [comment]
Understood.
Thank you.
