### ISSUE TITLE
 Make it compatible with electrolysis

### ISSUE THREAD

**Issue by moimael** [bhollis/jsonview#134]
Hi,

e10s start to be deployed to more and more people, and this addon is marked as not compatible with it.
Could you check if this is easily feasible ? From what I see it might need some work to port it to WebExtensions.

https://compatibility-lookup.services.mozilla.com/
https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

Thanks.

**Comment by bhollis** [comment]
I've already made it work on electrolysis a few times... not sure how much I want to chase Firefox's ever-changing requirements.

**Comment by synotna** [comment]
FYI https://addons.mozilla.org/en-US/firefox/addon/jsonovich/ does support multiprocess

**Comment by skylarmt** [comment]
FYI, I forced e10s with about:config, this addon seems to work fine with it enabled.

**Comment by bhollis** [comment]
Fixed by d98ad460464270d0fb84f985b48b9ee2ccc4ddaf
