### ISSUE TITLE
JSONView has been removed from the Chrome Web Store

### ISSUE THREAD

**Issue by mjamin** [bhollis/jsonview#135]
The extension is also automatically disabled with the notice that "this extension contains a serious security vulnerability."

**Comment by mattboroi** [comment]
[Related thread on HN](https://news.ycombinator.com/item?id=12925197#12925360)

**Comment by MicroDroid** [comment]
What is the cause of the removal? I'm confused.

I just had to re-enable the extension and it worked fine

**Comment by tordans** [comment]
The cached [google search result](http://webcache.googleusercontent.com/search?q=cache:cjMQO7tdlgAJ:https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc&num=1&hl=de&gl=de&strip=1&vwsrc=0) links to https://github.com/gildas-lormeau/JSONView-for-Chrome which interestingly did not have a issue ticket yet – it now has https://github.com/gildas-lormeau/JSONView-for-Chrome/issues/75.

**Comment by bhollis** [comment]
This is the GitHub repository for [JSONView](https://jsonview.com), the Firefox extension. "JSONView for Chrome" is an unofficial clone for Chrome and is not related to this project in any other way than having copied the name and logo.

**Comment by tordans** [comment]
@bhollis do you have any contact to @gildas-lormeau and could you ask him about his plans for the chrome plugin?

**Comment by bhollis** [comment]
No, I haven't ever had contact with him as far as I know.

**Comment by WaKeMaTTa** [comment]
jsonview will support chrome again?

**Comment by bhollis** [comment]
Again, this project has nothing to do with Chrome. 

-Ben

**Comment by WaKeMaTTa** [comment]
haha :laughing: Sorry then.
