### ISSUE TITLE
Valid json but not well formated, cloud not be parsed

### ISSUE THREAD

**Issue by briceruzand** [bhollis/jsonview#138]
The following valid json could not be parsed by jsonview 1.2.0.

https://gist.github.com/briceruzand/2481a83e739cea80a48b0d51ba93127b

I got the following error : 
`expected ':' after property name in object at line 5 column 14 `

**Comment by bhollis** [comment]
I guarantee it's not valid json. 

-Ben

**Comment by briceruzand** [comment]
Are you sure, because every jsonlint (validator) I try with that json tells it is a valid one. What is unvalid is that json ?

Thx

**Comment by bhollis** [comment]
You probably have some nonprintable character in there. I'd need to see the original document to be sure - whatever's in the Gist is valid, so it's not what JSONView is choking on.

**Comment by stanio** [comment]
Looks caused by the source tweaking done in `safeStringEncodeNums()` – the result becomes:

```json
{
  "status" : "ok",
"sort_by" : "asc",
"filters" : [],
"data" : {"i"​18"n":"label"}
}
```

**Comment by stanio** [comment]
So this looks related to #21 / 808e99f4ff41.  It fails to recognize the number is part of a string key, in the given case.

IMO, the fix for #21 should only target large _integer_ numbers (18+ decimal digits), while it appears to match any JSON number literal (including floating point numbers).

**Comment by bhollis** [comment]
Good catch! I'll see if I can tweak that refer. I've had no end of trouble with that patch. 

-Ben

**Comment by bhollis** [comment]
OK, it turned out to be a weird edge case in the regex to count quotes, not the number regex. I've fixed it. Sorry for doubting your issue, and thanks for sticking with it and helping fix a real bug!

**Comment by briceruzand** [comment]
Thank you guys for fixing this trouble.
Will you pulish a new release shortly with that fix ?

**Comment by stanio** [comment]
I already see it available at:

https://addons.mozilla.org/addon/jsonview/versions/

Probably it awaits formal AMO approval to appear directly on:

https://addons.mozilla.org/addon/jsonview/

**Comment by bhollis** [comment]
It has just been approved. 

-Ben

**Comment by stanio** [comment]
Unrelated... I've noticed the extension is marked that it doesn't require restart, but then JS updates don't really take effect until application gets restarted.

**Comment by briceruzand** [comment]
Thx very much my ugly json stream can now be visualized.
