### ISSUE TITLE
Error parsing escaped double quotes

### ISSUE THREAD

**Issue by de-cix-msauer** [bhollis/jsonview#141]
Hi,

somehow it now fails to parse properly escaped double quotes in string values.

`{
  "value":[
    {
      "@some.text":"W/\"12241774\""
    }
  ]
}
`

> expected ',' or '}' after property value in object at line 4 column 26

Never had this issues before. Seems to be new in 1.2.1.

**Comment by jgpacker** [comment]
Came here to report the same thing.

```json
{"name":"Smartphone Motorola Moto G4 PLUS XT1640 - Dual Chip,Tela 5.5\",Câmera 16MP+Frontal 5MP,Octa Core,32GB,2GB RAM,Android 6,Sensor impressão digital"}
```

**Comment by bhollis** [comment]
I'll try to push a fix tonight 

-Ben

**Comment by bhollis** [comment]
Didn't make it tonight but I'll get it out tomorrow. 

-Ben

**Comment by bhollis** [comment]
I've submitted a fix to addons.mozilla.org. That regex was more trouble than it was worth, so I just replaced it with some simple code that's guaranteed to be correct. You should see an updated addon in a day or so once Mozilla has reviewed it.

**Comment by cscorley** [comment]
I think I have a similar case (perhaps #142?), where the I receive this error:

```
There was an error parsing the JSON document. The document may not be well-formed.
expected ',' or '}' after property value in object at line 2 column 22
```

A minimal case:
```json
{
"dots":"\"v4.0\" \"v4.0\""
}
```

If I recall correctly, prior to 1.2.3 & 1.2.2, the error would occur on the period at the first period. In 1.2.3, the error occurs at the second.

**Comment by bhollis** [comment]
Thanks, I'll push out another fix for that. This is what I get for not putting my full attention on this.

**Comment by bhollis** [comment]
That fix has been released.

**Comment by cscorley** [comment]
@bhollis Excellent! Thank you for your work.
