### ISSUE TITLE
Problem parsing valid JSON string with escaped double quotes in the values

### ISSUE THREAD

**Issue by berckoff** [bhollis/jsonview#143]
Hey there,
i have updated my FF to the latest version and now this issue occurs:
when the result contains escaped double quotes the plugin says
"There was an error parsing the JSON document. The document may not be well-formed.
expected ',' or '}' after property value in object at line 1 column 503 ".

And the JSON string is:
{"response":{"subscriptions":{"35900100953":{"address":"6000 СТАРА ЗАГОРА, ул. \"ВИТ\" 0, вх. 0, ет. 0, ап. 0"}}}}

Is this a possible problem with the new version of FF?

**Comment by bhollis** [comment]
There's a fixed version waiting for Mozilla approval. Thanks for letting me know!

-Ben

**Comment by kilroy59** [comment]
I was going to report same issue, glad to hear it's fixed & look forwsrd to the update. BTW, great Add-on!
