### ISSUE TITLE
Example.json illegally starts with BOM

### ISSUE THREAD

**Issue by knime** [bhollis/jsonview#144]
The example.json file shown on the web page and used in the tests is not valid JSON. It starts with a BOM, which the JSON RFC explicitly forbids (see https://tools.ietf.org/html/rfc7159#section-8.1).

**Comment by bhollis** [comment]
Good point. It's not perfectly valid, but I've run across enough documents that do have a BOM that I wanted to make sure the add on wouldn't barf on them so it's in the example. 

-Ben

**Comment by knime** [comment]
The problem is that some of our users used your example file with our software and then claimed our software is faulty because it correctly refused to parse the file (the Jackson library for a matter of fact). This caused several hours of debugging on our end just to find out the input was garbage.
