### ISSUE TITLE
Failing to parse valid JSON - quote escaping issue?

### ISSUE THREAD

**Issue by gbradley** [bhollis/jsonview#147]
I'm using v1.2.4 and JSONView is failing to parse JSON returned from the Twitter API - see https://gist.github.com/gbradley/a6a6e59871b15af25dd3b5b78c66778c for example data.

**Comment by bhollis** [comment]
Works fine for me when I save that data to a .json file and open it in Firefox 54. What version of Firefox are you using?

**Comment by gbradley** [comment]
Turns out this was caused by an intermittent content-type issue - sorry!
