### ISSUE TITLE
Port to WebExtensions

### ISSUE THREAD

**Issue by garak** [bhollis/jsonview#149]
This addon has been marked as "legacy" in about:addons on recently released Firefox 55, due to the transition to WebExtensions in Firefox 57. Legacy addons are no longer supported since June on nightly and developer channels.

This [MDN comparison between the SDK and WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Comparison_with_the_Add-on_SDK) seems like a good starting place to look.

**Comment by bhollis** [comment]
Unfortunately, WebExtensions are not capable of replicating the way JSONView works. I could make a poor approximation (as the Chrome port did) but I haven't decided if I'd be satisfied with that, as it's a dangerous kludge. More likely, this decision by Firefox will be the end of JSONView. 

-Ben

**Comment by garak** [comment]
Sad to hear that. So, I moved for JSON Lite for now.
Thank you for your reply.
