### ISSUE TITLE
Support for Firefox 57

### ISSUE THREAD

**Issue by mitar** [bhollis/jsonview#152]
It seems this plugin will be disabled in Firefox 57. :-(

**Comment by yfdyh000** [comment]
See #151.

**Comment by mitar** [comment]
I checked the built-in JSON viewer, but it is terrible. Arrays are displayed like an object.

**Comment by zhengb302** [comment]
It is still disabled in Firefox 57.

**Comment by nikunjahuja** [comment]
After updating my Mac this add-on got disable and becomes incompatible
![screen shot 2017-11-22 at 1 21 02 pm](https://user-images.githubusercontent.com/25298346/33115806-4eed7b0c-cf88-11e7-9c4b-a0d52b57aa6b.png)

**Comment by herrernst** [comment]
JSONView was my favourite JSON add-on, would be glad if it would work in FF Quantum.

**Comment by bhollis** [comment]
JSONView will support Quantum in a few months.

**Comment by kaecy** [comment]
In a few months? We can't wait that long. Okay i'll wait. 😃

**Comment by jaraco** [comment]
I've posted a bounty for this issue.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50745453)](https://www.bountysource.com/issues/50745453-support-for-firefox-57?utm_source=50745453&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Please consider adding to the bounty to encourage and reward @bhollis.

**Comment by modder2** [comment]
@bhollis we believe in you! 😉

**Comment by jeffjensen** [comment]
I've tried a few others as replacements and none are as useful as jsonview.

**Comment by MichaelRoehrig** [comment]
As far as I can see, Firefox now supports _application/hal+json_ natively. It show the standard JSON firefox view with the tree view, raw json and headers.

**Comment by kaecy** [comment]
If you still want to use this extension you can with [waterfox](https://www.waterfoxproject.org). There is life left in this extension.

![](https://user-images.githubusercontent.com/4354982/39732097-4adcd54a-5263-11e8-8b44-cc08e8fcce4f.png)

**Comment by Vampire** [comment]
And this helps in using the extension with Firefox how?
You can also stay with a pre-WebExtensions version of Firefox to continue using it.
But that does help the same, which is, almost not.

**Comment by bhollis** [comment]
JSONView will be compatible with modern Firefox soon, potentially this weekend.

**Comment by kaecy** [comment]
Waterfox not only supports old extensions but newer chrome style ones too. It's a win-win!

**Comment by Vampire** [comment]
@kaecy a browser is not only about extensions. It is also about support, maintenance bug-fixes and continued development. Can you estimate on these? Besides that, Bing as default search engine? Really? :astonished:

**Comment by kaecy** [comment]
It's your choice. I'm not forcing you. If you have questions you can ask them at waterfox forums.

**Comment by bhollis** [comment]
JSONView is now compatible with Firefox 57+ and Google Chrome.

**Comment by kaecy** [comment]
Awesome! It works with waterfox/56.1. To install from addons.mozilla.org you have to change the user_agent to Firefox/57.

**Comment by jaraco** [comment]
Love it! Works for me. Don't forget to claim your (modest) bounty.
