### ISSUE TITLE
Support view on .json local files

### ISSUE THREAD

**Issue by mitar** [bhollis/jsonview#153]
With latest release it seems it is not possible to open a .json local file and get it rendered (tested in Firefox).

**Comment by bhollis** [comment]
How are you opening it? This works for me when dragging a JSON file into Firefox.

**Comment by mitar** [comment]
Yes, but the default Firefox viewer displays it, not this extension. So I just click File -> Open File and select a file with `.json` extension.

**Comment by bhollis** [comment]
Are you using Firefox Developer Edition?

**Comment by mitar** [comment]
No, I am using Firefox 60, on Ubuntu.

**Comment by bhollis** [comment]
I’m not sure, then. Perhaps you need to go into about:config and disable the built-in Firefox JSON viewer?

**Comment by mitar** [comment]
Oh, you are right. Once disabled it works. Maybe you should put this into instructions somewhere? (Or have I missed it and is already there?)

**Comment by mitar** [comment]
Oh, you are right. Once disabled it works. Maybe you should put this into instructions somewhere? (Or have I missed it and is already there?)
