### ISSUE TITLE
Display problem with expand arrows and collapsed sections

### ISSUE THREAD

**Issue by dregad** [bhollis/jsonview#154]
I just installed the new JSONview 2.0.0 (on FF 58.0.1) and I'm seeing strange display on [this webservice](https://www.ville-geneve.ch/themes/environnement-urbain-espaces-verts/espaces-verts/iparc/jsonurl/urljsons/listUrljsons/json/typeUrljsons/) (see attached screenshot) - maybe some kind of UTF8 encoding issue ?

![screenshot-20180516-1608](https://user-images.githubusercontent.com/449891/40122240-a3a5c0bc-5923-11e8-8578-b2e63768f696.png)

Note, problem does not occur with the sample json at https://jsonview.com/example.json

**Comment by bhollis** [comment]
JSONView 2.0.1 has been released that fixes this. Thank you for the report!

**Comment by dregad** [comment]
Thanks for the prompt response. I confirm that 2.0.1 does fix the problem.

**Comment by ernstki** [comment]
This seems to be back (for me), on Chrome 78.0.something and version 2.1.0 of the extension.

Do you recall if it had anything to do with the remote server, maybe, not sending the right encoding, or something do do with locale (language) settings?

We have an internal API on a server that transmits `Content-Type: application/json; charset=ISO-8859-1`, but I don't see this problem, on, say, the GitHub Jobs API, which sends `application/json; charset=utf-8`.

**Comment by bhollis** [comment]
The JSON spec mandates that it is UTF-8 encoded. If it's not UTF-8, it's not JSON.

**Comment by ernstki** [comment]
Oh, well that solves it. Thanks for upgrading my knowledge.
