### ISSUE TITLE
build.sh assumes jsonview.zip exists, uses pushd on /bin/sh

### ISSUE THREAD

**Issue by dmick** [bhollis/jsonview#160]
build.sh fails on first build because there's no jsonview.zip.  Also, although it's coded with #!/bin/sh, it uses pushd and popd, which aren't in /bin/sh if /bin/sh is a limited Bourne-type shell (like dash on Ubuntu).

both easily fixed.

**Comment by bhollis** [comment]
Thanks for letting me know. I’d be happy to review a PR that fixes this.

**Comment by dmick** [comment]
Did you intend to close it?  I'll submit a PR
