### ISSUE TITLE
keys are being reordered for tree view

### ISSUE THREAD

**Issue by joetym** [bhollis/jsonview#162]
Opening this:  

{"data":{"STRING1":-10,"0":-0.1,"1":0,"STRING2":20}}

In the nice tree view, keys are re-ordered to:  

0,1,STRING1,STRING2

Would be nicer if they stay in the order they are in the JSON.

Using Firefox Quantum 64.0.2 (64-bit)

**Comment by bhollis** [comment]
Unfortunately order isn’t guaranteed - we just show whatever the browser’s JSON parser ends up doing.

**Comment by joetym** [comment]
Should I raise it as a firefox issue then ?

**Comment by bhollis** [comment]
That sounds best.

**Comment by joetym** [comment]
It does the same thing in Chrome. Any idea why that might be ?

**Comment by joetym** [comment]
Seems they all do the same thing,

https://stackoverflow.com/questions/5020699/how-do-you-stop-chrome-and-opera-sorting-json-objects-by-index-asc

You can stop it by adding something non-numeric to the key _ or i perhaps, seems like a bit of a hack but I'll got with it. Would it be interesting to know why they thought this was a good idea.
