### ISSUE TITLE
Using HTML entity '&quot;' breaks valid JSON

### ISSUE THREAD

**Issue by ChrisSVC** [bhollis/jsonview#164]
Strings within valid JSON that happen to include the HTML entity `&quot;` results in the JSON displaying as text in Chrome. Presumably this is because JSONView sees it as a " so ends the value string, therefore treating the next part of the string as JSON which it then finds to be invalid.

For example this:
{"status":"success","data":{"name":"Dave","hair_colour":"So-called `&quot;`Strawberry-blonde`&quot;`"}}
Is being treated like this:
{"status":"success","data":{"name":"Dave","hair_colour":"So-called "Strawberry-blonde""}}
which is obviously invalid.

Would be nice if it didn't do that for debugging the use of strings containing quotes captured in HTML in JSON.

**Comment by bhollis** [comment]
![image](https://user-images.githubusercontent.com/313208/66271879-ff804900-e817-11e9-86b3-019d08055b03.png)

I'm unable to reproduce this. Are you sure you're using the real JSONView? https://chrome.google.com/webstore/detail/jsonview/gmegofmjomhknnokphhckolhcffdaihd

**Comment by ChrisSVC** [comment]
Apologies, looks like I’m using the other product called JSONView on the Chrome store. Didn’t realise there were two.
