### ISSUE TITLE
Error when parsing hbs files

### ISSUE THREAD

**Issue by artemgurzhii** [bhollis/jsonview#167]
I'm having [this error](https://monosnap.com/file/lMZ9mzEEOgHNs7GYrI6kAwvpBlB0ry) when opening raw `hbs` file. It looks like error only occurs when file content starts with the `{` sign.
See an example here - [link 1](https://raw.githubusercontent.com/wycats/handlebars.js/master/spec/artifacts/example_1.handlebars#)

See an example here - [link 2](https://raw.githubusercontent.com/wycats/handlebars.js/master/integration-testing/webpack-test/src/test-template.handlebars). The second example does not throw an error, and I guess it's because the first character is not `{`.

So, my assumption is that JSON view trying to beatify content if the file starts with the `{`. In that case, we can try to skip the beatifying content of the file unless the URL ends with `.json` or has no extension at all. Then in the case of `.{js,hbs,any_other,...}` extension - no error will be thrown.

P.S. I can help with the fix, once we confirm which option is better. Thank you.

**Comment by bhollis** [comment]
Neither of those files is JSON.

**Comment by artemgurzhii** [comment]
@bhollis Emm, I know and that's the problem :) JSON view extension is trying to parse those files even though they are not JSON, please open link 1 and link 2

**Comment by artemgurzhii** [comment]
@bhollis please, reopen the issue
