### ISSUE TITLE
OAuth2 redirection flows are intercepted and continued with wrong content type

### ISSUE THREAD

**Issue by almereyda** [bhollis/jsonview#170]
While the plugin continues to work here, in opposition to the observation from #168, and successfully takes over Firefox' native JSON rendering, it appears it also interferes with some OAuth2 redirection flows and does not allow them to complete sufficiently.

During the callback dance, some requests respond with JSON, and redirect to HTML pages afterwards. Unfortunately, Firefox will try to interpret those as JSON, when the plugin is left active.

This happened during local development and a dance between `http://localhost:3000` and an OAuth2 provider on `https`.

**Comment by jonwolski** [comment]
A scripted a tiny http server to demonstrate the problem:

https://gist.github.com/jonwolski/27f6b974474051b8ccd3440ff68dba54

It seems to arise when there is a `content-type` on a redirect response. The subsequent response gets interpreted with the redirect response's content-type.

**Comment by bhollis** [comment]
Yup I just haven't gotten around to releasing a new version

**Comment by bhollis** [comment]
Published a new version. It's out for Firefox, still in review for Chrome
