### ISSUE TITLE
Is there JSONView for Edge?

### ISSUE THREAD

**Issue by Andre601** [bhollis/jsonview#171]
I've recently switched from Chrome to Edge (which now uses Chromium) and while Edge allowed me to import Extensions, including those only available on the Chrome/Firefox store would I appreciate it a lot, if there is an official version for Edge.

I found an extension called [JSONView])(https://microsoftedge.microsoft.com/addons/detail/jsonview/biaiohdllmhjchjdhgamfmdjfhpbaohf?hl=en) which uses the exact same (or a nierly identical) icon as the chrome version does.
But since I couldn't find any clue about if this extension is trustworthy did I not install it yet and wanted to ask here, if there is a usable version of JSONView, that is for Edge and that is official (as in you support it in case of bugs and similar).

If there isn't a version for edge would I appreciate, if you could either have one for it, or recommend me an alternative for it.

Thanks

**Comment by bhollis** [comment]
Nah, I don't really want to pay $20 to list it.

**Comment by nagachaitanyalokam** [comment]
Hello @bhollis, 

There's no registration fees involved to register and publish your extension on Microsoft Edge Store.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.
