### ISSUE TITLE
Add toggle/option to have a dark background (dark theme)

### ISSUE THREAD

**Issue by Andre601** [bhollis/jsonview#176]
People like me prefer to utilize dark themes on various websites, as it is sometimes easier for the eyes. But when I use JSONView does it cause my eyes to hurt as it is an extreme white background compared to the usual dark gray, black, etc. my eyes are used to.

So with this issue would I like to request a setting/toggle where you can switch to a dark theme version for the JSON displayed.
From the JSON I saw so far would it seem that the biggest changes would be a different bg color, text color for the keys (not values like "Strings") and maybe a brighter blue for the numbers.

I would really appreciate if this could be considered as I am more used to dark themes but also use JSON stuff periodically, so this can be somewhat annoying.

**Comment by bhollis** [comment]
I won't add an option, but I've made a change to respect the system dark mode preference.

**Comment by Andre601** [comment]
That seems fair enough
