### ISSUE TITLE
add font size to options menu

### ISSUE THREAD

**Issue by mlongoria1** [bhollis/jsonview#185]
This is more of a request than an issue, please redirect if this is not posted in the correct place.

Can you add a font-size option in the options menu? The font on my jsonview tab/page is smaller than the rest of my tabs/pages. Can you guys increase the font size a little or add the option for users to change the font size in the plugin itself?

If you need any more info feel free to ask.

Thank you.

**Comment by bhollis** [comment]
You can zoom in your browser using Cmd/Ctrl +

**Comment by mlongoria1** [comment]
I have tried that already, it was the first thing I did actually. 

But then you have to unzoom when you move from the JSONized(if that's a word) page while troubleshooting the original webapp/webpage that is using the JSON code, and then zoom in again when going back to the JSON page. If a font size was able to be set in the plugin then, all the rest of my tabs/pages will not be affected since they are set at the appropriate zoom setting that I am used to and only the JSON viewed page will be affected.

I hope this makes sense.

Thank you,

**Comment by mlongoria1** [comment]
Here is another plugin that I have been using as you can see the font is larger than JSONview's by default:
![PQycmTyGhX](https://user-images.githubusercontent.com/38320817/141513974-db6b7fb3-9f1b-498d-9576-317a8897d3e0.png)

Here is JSONview, it is a lot smaller:
![4Sb2qu6sNR](https://user-images.githubusercontent.com/38320817/141514117-925604cd-ef12-4d3e-a25b-db303b01c0e5.png)

**Comment by bhollis** [comment]
I don't think I want to add an option for this. Do you know if there's a way to convince the browser to apply font sizing only for a single page?

**Comment by stanio** [comment]
JSONView already applies a bigger than the default font-size:

```css
#json {
  font-family: monospace;
  font-size: 1.1em;
```

For that purpose, I have the opposite problem of this being too big for my preference so I adjust it via user styles.

> Here is JSONview, it is a lot smaller:

The given screenshot doesn't appear from a genuine JSONView – there's a background color applied to the inner content and the collapsers are not arrows but look like `-` (minus/hyphen).  I can see there's same-named extension for Chrome:

-   https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc

@mlongoria1, have you installed that and not the following one?

-   https://chrome.google.com/webstore/detail/jsonview/gmegofmjomhknnokphhckolhcffdaihd

The last one is linked from https://jsonview.com/

**Comment by mlongoria1** [comment]
@bhollis According to this link:
https://superuser.com/questions/677967/chrome-any-way-to-zoom-a-single-page-not-all-pages-in-domain

There is not "a way to convince the browser to apply font sizing only for a single page." 

I was doing a lot of research before posting my request. I thought the request would be the easiest route to get my issue fixed at this point... I understand if you do not want to add the feature but if you don't ask you won't receive right??? LoL

**Comment by bhollis** [comment]
Yep, understood. I don't want to add a bunch of options to the addon though, it's meant to be ultra simple. Also as @stanio mentioned it looks like you are using a different extension than the official JSONView.

**Comment by mlongoria1** [comment]
Yes @stanio was correct. I was using the "other guy's" extension. But now that I am using yours it seems to not work at all. Can you guys try to help me get it working? I used the link @stanio sent us up above...

Check it out, you can see the extension is installed by not working/enabled
![QsHsFUKkfm](https://user-images.githubusercontent.com/38320817/141530158-3e5ed4c2-3f4a-4988-978b-e05b220e0328.png)
:


Am I missing something, do I have to enable it on specific sites or should it just work?

**Comment by stanio** [comment]
> There is not "a way to convince the browser to apply font sizing only for a single page."

Using extensions like [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) allows you to apply user styles to a single page (URL) or group of pages (URL-prefix, URLs on a domain, or URLs matching regexp).  For my purpose of adjusting the JSONView font size, I apply the particular style to all content (URLs) but I make the style specific enough, so it applies only to JSONView rendering:

```css
html:root > body > #json {
  font-size: unset;
}
```

FWIW, I use Firefox, and not Chrome.

> Check it out, you can see the extension is installed by not working/enabled

Dunno what's happening on your side.  Try uninstalling all of the JSONView extensions you have, then reinstall just one of them.
