### ISSUE TITLE
Add support for Content-Type: application/vnd.spring-boot.actuator.v3+json

### ISSUE THREAD

**Issue by Rickroll-C137** [bhollis/jsonview#188]
When you visiting the springboot actuator web monitor page, it will return a json string of the opened ports. The problem is that the response Content-Type header is application/vnd.spring-boot.actuator.v3+json, thus can`t be recognized as json string by jsonview.

**Comment by stanio** [comment]
As far as I can see the regex (#179) needs to be further adjusted to match `-` (hyphen) and digits:

```ts
const jsonContentType = /^application\/([a-z.]+\+)?json($|;)/;
```
