### ISSUE TITLE
Copy json loses indention

### ISSUE THREAD

**Issue by agilenut** [bhollis/jsonview#191]
I really like your plugin. Great work. 

One issue I have is that when I copy the formatted json, it seems to lose all of its indention. 

Is it possible to retain the indention when copying?

**Comment by samuelbarrionuevo** [comment]
good, I had the same problem of the sangria

**Comment by agilenut** [comment]
@bhollis - I'm using the latest version of Edge on Windows 10. I installed JSONView from Microsoft Edge Add-ons Marketplace. I highlight the entire JSON text in the browser using ctrl+A, copy with cntrl+C, and then paste into Notepad or Notepad++. 

I just tested again and it is still losing all indentation.

**Comment by bhollis** [comment]
Ah, I totally forgot about Edge. Let me publish the new version there too.

**Comment by bhollis** [comment]
Hmm, looks like Edge no longer allows Manifest V2 extensions. This'll have to wait until https://github.com/bhollis/jsonview/issues/199.

**Comment by agilenut** [comment]
Okay. Thank you.
