### ISSUE TITLE
The extension doesn't work

### ISSUE THREAD

**Issue by desbest** [bhollis/jsonview#192]
Hello your extension doesn't work. When I open these .json files, I don't get any syntax highlighting or code beautifying/prettifying.

Are you only looking for the Content-Type HTTP header and not the file extension?

Try it yourself and test it out with these URL's

https://raw.githubusercontent.com/HuiiBuh/InstagramDownloader/master/src/tsconfig.json

https://gitlab.com/-/snippets/2385140/raw/main/pictureflect%20saved%20effect%20list.json

**Comment by adv0r** [comment]
let me add https://yt.lemnoslife.com/videos?part=mostReplayed&id=NIJ5RiMAmNs to the feature request :D

**Comment by bhollis** [comment]
The documentation clearly states that the extension works off of content-type - if the file is served incorrectly, the extension won't check it.
