### ISSUE TITLE
AWS Console usage triggers JsonView trying to parse an HTML page in error

### ISSUE THREAD

**Issue by mr-sebbo** [bhollis/jsonview#198]
Thanks for a great plugin!
Seems that aws console navigation functionality triggers jsonview when re-rendering the page.
CTRL+F5 allows the page to render correctly.
Disabling JsonView fixes the problem.
This post describes the error:
https://support.mozilla.org/fy-NL/questions/1294025
Thanks

**Comment by stanio** [comment]
I've seen this in the past.  If I remember correctly it was caused by another extension I had installed and stopped occurring after I disabled that particular other extension.  Try disabling all but JSONView to verify.
