### ISSUE TITLE
Wrong character instead of triangle pointing down

### ISSUE THREAD

**Issue by germancecch** [bhollis/jsonview#200]
**Describe the bug**
The plugin worked fine for many months. With the last update 2.4.0, the downward pointing triangle to expand/retract nodes was replaced by an A character rotated 90' 
[Image](https://postimg.cc/n9Vxdnzr)

**What browser are you using?***
Firefox 112.0.2 in Ubuntu 22.04.2 LTS
In chrome works fine.

**Where did you install JSONView from?**
[Home page](https://jsonview.com/)

**Comment by bhollis** [comment]
That's pretty exciting - I don't think anything changed with how that works.

**Comment by germancecch** [comment]
Maybe this commit?
https://github.com/bhollis/jsonview/commit/8b2b327ca5237c89b62ab89e47c7da5ee0a94e27#diff-11db236acd6b02b1229e7d325e9bf8edb521032e6388f68b6a884ec24bbe291fR36

**Comment by bhollis** [comment]
Yes they have to review it. No idea how long that will take, Firefox has about a week's lag these days.

**Comment by balagez** [comment]
I have 2.4.1 and the issue is still present: [screenshot](https://github.com/bhollis/jsonview/assets/862067/060d274f-ad0f-4b1d-bb94-419e6b745634)
And it's not only the arrows but basically any UTF-8 text, like Japanese here: [screenshot](https://github.com/bhollis/jsonview/assets/862067/1b9151ee-88de-4d33-b94b-7073fe49cc45)

**Comment by germancecch** [comment]
Problem solved with 2.4.1. 

TY!

**Comment by balagez** [comment]
No it's not. I already have that: <img width="690" alt="Screenshot 2023-05-16 at 10 44 25" src="https://github.com/bhollis/jsonview/assets/862067/e8c57b8e-7944-40f1-82e6-39097240a2fc">

**Comment by stanio** [comment]
@balagez, are you able to see https://jsonview.com/example.json fine?

**Comment by balagez** [comment]
@stanio Yes that works. Here's an example that doesn't: https://kinja.com/api/core/post/search?query=language:ja

**Comment by germancecch** [comment]
The [rfc8259](https://www.rfc-editor.org/rfc/rfc8259.html) defines that: 
```
Note:  No "charset" parameter is defined for this registration.
      Adding one really has no effect on compliant recipients.
```

I thing the plugin must assume utf-8 if no content-type/charset is received.

**Comment by stanio** [comment]
> Here's an example that doesn't: https://kinja.com/api/core/post/1849599382

FWIW, on that "page" I'm seeing the "Repair Text Encoding" item active:

![shot1](https://github.com/bhollis/jsonview/assets/1247730/f02946ed-ffdf-4e4a-ba83-0e2afacce1c3)

![shot2](https://github.com/bhollis/jsonview/assets/1247730/3254768d-c417-4b88-bd73-6b9cb6a852e3)

After activating it the content is seen fine:

![shot3](https://github.com/bhollis/jsonview/assets/1247730/cf2beb61-62b0-4d97-869a-e01c1720fcb1)

Not sure what's going on.  Saving the file locally with a `.json` extension and opening that in Firefox, displays it fine this time around.

**Comment by bhollis** [comment]
For later reference it appears that this only happens on Firefox?

**Comment by bhollis** [comment]
MS Edge hasn't updated because they no longer accept this extension.

**Comment by stanio** [comment]
In both of my Firefox and Edge extensions, I'm seeing JSONView Version 2.4.1.  Could be I've installed it from the Chrome Web Store, don't really remember.

**Comment by balagez** [comment]
Now it's working as expected. Whether or not the server should send the encoding is almost a decade old debate, and and both Chromium and Firefox seem to have been non-compliant at some point in the past:

* https://bugs.chromium.org/p/chromium/issues/detail?id=438464
* https://github.com/playframework/playframework/pull/5738

Up until recently Firefox handled it well so I assume it's a recent regression in Firefox. Anyways, thank you for fixing it.

**Comment by Hanmac** [comment]
i still get the same problem with 2.6.1 in Firefox 121.0.1

The Fix Encoding Button fixes it temporarly

**Comment by blkhwks19** [comment]
@bhollis I'm still getting the same issue with 2.6.1 in Firefox 124.0.2. However I do NOT have the "Repair Text Encoding" option available. It's grayed out, so I can't use that as a temporary fix. Screenshot from [REST Countries API](https://restcountries.com/v2/all) below.
![screenshot](https://github.com/bhollis/jsonview/assets/3278774/78d3fce5-6e84-49f6-96f2-a67fa3a99f59)
