### ISSUE TITLE
Error handling response: TypeError: Cannot read properties of undefined (reading 'textContent')

### ISSUE THREAD

**Issue by tasselx** [bhollis/jsonview#208]
**Describe the bug**
Unable to display json properly and reporting errors in the console

![409952260](https://github.com/bhollis/jsonview/assets/2656142/503c09d5-4e80-4f8e-a6c3-e0f1e917d4db)

**What browser are you using?***
Microsoft Edge for Mac
version: 116.0.1938.54 (正式版本) (arm64)
The plugin version number used is 2.4.3

**Where did you install JSONView from?**
edge's plugin store installed

**Comment by bhollis** [comment]
This would be the line: https://github.com/bhollis/jsonview/blob/master/src/content.ts#L28

However it works for me on Chrome and Edge. So I suspect you have another extension that's changing the content and making this fail.

**Comment by bhollis** [comment]
For reference, with no extensions enabled at all, this is what JSON looks like:

<img width="1884" alt="image" src="https://github.com/bhollis/jsonview/assets/313208/688e9aa5-4291-473b-a944-32387a088194">

So the fact that you have line numbers and such suggests you have another extension operating on the content that is incompatible with JSONView.

**Comment by tasselx** [comment]
> This would be the line: https://github.com/bhollis/jsonview/blob/master/src/content.ts#L28
> 
> However it works for me on Chrome and Edge. So I suspect you have another extension that's changing the content and making this fail.

I tried disabling all browser extensions, as well as the grease monkey script, leaving only the jsonview, and still no way to display the json properly.At the time I had this problem, it was my edge browser upgraded to the latest version, not ruling out browser compatibility issues? @bhollis 

![image](https://github.com/bhollis/jsonview/assets/2656142/c906747b-7e39-4d6a-89dd-6023240e4342)

**Comment by tasselx** [comment]
The new version of edge comes with JSON formatting and disables other JSON extensions. You need to find JSON Viewer in edge://flags/, set it to disable
