### ISSUE TITLE
version 2.5.0 - jsonview not displaying

### ISSUE THREAD

**Issue by rbro** [bhollis/jsonview#209]
After updating to JSONView 2.5.0, I'm not able to view json files using JSONView.  The json files are instead rendered using Firefox's default jsonviewer.  Did something change in the new version to cause this?

Thanks for your help.

**Comment by bhollis** [comment]
Nothing has specifically changed about that, you still have to disable Firefox's built in JSON viewer to use JSONView.

**Comment by rbro** [comment]
Thanks, that fixed it.  Interesting, I've used JSONView for many years and never had to disable it before.  My application is sending the application/json content-type.  Either way, thanks for your quick help and response.

**Comment by rbro** [comment]
If it's useful, I just tried a fresh install of Firefox with JSONView 2.4.3.  I was able to go to https://jsonview.com/example.json and the json rendered through JSONView.  I then upgraded to JSONView 2.5.0 and https://jsonview.com/example.json now rendered with the native Firefox viewer.  Setting "devtools.jsonview.enabled = false" gets around it, but I didn't need to do that in version 2.4.3 and earlier.

**Comment by bhollis** [comment]
Interesting, I'll take a look. I thought you always had to change it but I don't really use Firefox other than whenever I update JSONView.

**Comment by bhollis** [comment]
I've uploaded a new version to AMO that should fix this. It'll break if Mozilla ever requires Manifest V3...

**Comment by rbro** [comment]
Thanks for the quick update.  I'll start updating my machines to disable the native viewer if they ever remove Manifest V2 one day.
