### ISSUE TITLE
AMO page's description outdated

### ISSUE THREAD

**Issue by Chealer** [bhollis/jsonview#211]
The _About this extension_ section of [JSONView's page on addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/jsonview/) starts with:

> Normally when encountering a JSON document (content type "application/json"), Firefox simply prompts you to download the file.

This is pretty outdated, since [Firefox's built-in JSON viewer](https://firefox-source-docs.mozilla.org/devtools-user/json_viewer/index.html) was enabled by default in version 53 (April 2017).

It would be good to replace this with a description of what JSONView currently brings to Firefox.

**Comment by bhollis** [comment]
Done (for English). I haven't really used Firefox in a decade but it's nice to know folks find the built-in JSON viewer useful.

**Comment by Chealer** [comment]
Thank you very much Ben

If I may, I suggest clarifying the following sentence:

> Even if the JSON document contains errors, JSONView will still show the raw text.

...indicating whether Firefox's built-in viewer can do the same, and ideally specifying that this (surely) only refers to *syntax* errors. Perhaps:
> Unlike Firefox's built-in viewer, JSONView will show the document's content raw if it does not use proper JSON (i.e. if it is syntactically invalid).

**Comment by bhollis** [comment]
I have no idea what Firefox's built in viewer can and cannot do - my assumption is that if people are happy with the built in version they will not be seeking to install JSONView in the first place.
