### ISSUE TITLE
Support .jsonc files?

### ISSUE THREAD

**Issue by WybeBosch** [bhollis/jsonview#212]
Hi there, any chance your extension could also support "JSON with comment files?" it seems it tries to open them, 
but then runs into issues trying to get past the comments.

<img width="1514" alt="image" src="https://github.com/bhollis/jsonview/assets/40889930/2b678f60-c06e-4925-9a07-192a446b42e8">

**Comment by bhollis** [comment]
I understand the desire but this extension is just for JSON, not related formats.

**Comment by WybeBosch** [comment]
Ah i understand no problem. Is there a way to exclude files from being picked up by the extension?

**Comment by bhollis** [comment]
JSONView only cares about the content-type of the response. If you serve `application/json` it needs to be real JSON.
