### ISSUE TITLE
Unexpected non-whitespace character after JSON at position 256 (line 1 column 257)

### ISSUE THREAD

**Issue by tasselx** [bhollis/jsonview#213]
**Describe the bug**
When I open this example json file, this error message pops up https://jsonview.com/example.json.

**What browser are you using?***
Its version is 2.6.1, and it uses Microsoft's Edge browser for Mac, with the version number 123.0.2420.65.

**Where did you install JSONView from?**
Installed JSONView from the Microsoft Edge browser's extension marketplace.

![3170125211](https://github.com/bhollis/jsonview/assets/2656142/93c65cf0-b199-4a2f-9f66-955eff2901f7)

**Comment by bhollis** [comment]
There does seem to be some problem with the Chinese version of Edge. Unfortunately I can't easily reproduce on my own versions of Edge or Chrome. Any ideas what would be different?

**Comment by stanio** [comment]
I'm seeing it with the English version (123.0.2420.65) of Edge on Windows 10:

![screenshot](https://github.com/bhollis/jsonview/assets/1247730/5213e842-ced3-4733-914f-fa622b22b8f4)

JSONView 2.6.1 installed from the Chrome Web Store.  It opens fine using JSONView 2.6.1 on Firefox.

**Comment by bhollis** [comment]
Interesting! This would be a good puzzle for someone who has the free time (i.e. not me) to figure out and fix. A good starting point for the investigation would be that:

1. This appears to be specific to Edge.
2. The phrase "Code folding" does not come from anywhere in JSONView's code.
3. JSONView in Chrome-based browsers uses the contents of the browser's default HTML-ization of the JSON text, which up until now consisted of just the JSON text in a `<pre>` tag.

**Comment by bhollis** [comment]
This should be fixed whenever 3.0.0 gets approved.
