### ISSUE TITLE
inserts double quotes 

### ISSUE THREAD

**Issue by mzimmersfluidra** [bhollis/jsonview#214]
**Describe the bug**
Sometimes the first element in an object is enclosed in double quotes. The quotes are definitely not coming from the JSON generator.

**What browser are you using?***
Chrome (latest)

**Where did you install JSONView from?**
Chrome store
![Screenshot 2024-04-17 093127](https://github.com/bhollis/jsonview/assets/105254602/ef7440cd-3276-4bd8-b663-1cd212388a89)

**Comment by bhollis** [comment]
This should be fixed whenever 3.0.0 gets approved.
