### ISSUE TITLE
JSON number is being truncated as if it was an integer

### ISSUE THREAD

**Issue by scott-mcdonald** [bhollis/jsonview#216]
**Describe the bug**
The JSON number type is being truncated to an integer.

I have for example JSON numbers that represent distance with a whole and fractional part. The fractional part is being truncated. When I look at the raw JSON the number is correct with both a whole and fractional parts for distance.

Also for Chrome, looking at the developer tools and seeing what the JSON response is from the API server the JSON is correct. Then I noticed you just did a major upgrade to 3.0 on 6/17 which explains it as this was working previously...

**What browser are you using?***
Chrome

**Where did you install JSONView from?**
Chrome WebStore

**Comment by bhollis** [comment]
You're right, I spotted the issue. I'll release an update tonight.

**Comment by bhollis** [comment]
Submitted as 3.0.1. It's up to the web stores to publish it now.

**Comment by scott-mcdonald** [comment]
Thank you @bhollis FYI I am currently seeing the problem on Firefox. You want me to create another issue or it is not needed and Firefox will correct itself once your latest version is propagated downstream to my local Firefox browser?

**Comment by stanio** [comment]
FWIW, I'm still not seeing v3.0.1 available on AMO: https://addons.mozilla.org/firefox/addon/jsonview/

**Comment by bhollis** [comment]
Yes, the Mozilla team takes up to a week to approve any update.

**Comment by bhollis** [comment]
OK now it's been updated with Mozilla.
