### ISSUE TITLE
Protocol relative URLs are not turned into hyperlink

### ISSUE THREAD

**Issue by jong99** [bhollis/jsonview#44]
Not sure how to easily & reliably detect these, but it would be great if protocol-relative URLs (see http://tools.ietf.org/html/rfc3986#section-4.2) could be turned into hyperlinks.  For example:

``` json
{
    "href": "//www.google.com/",
}
```

I would expect the html fragment for this link to be:

``` html
<a href="//www.google.com/">//www.google.com/</a>
```

**Comment by saikatguha** [comment]
HATEOAS (https://en.wikipedia.org/wiki/HATEOAS), HAL (http://tools.ietf.org/html/draft-kelly-json-hal-07), and many RESTful cookbooks recommend embedding resource links inside JSON. Often these links are relative URLs. 

Thoughts on adding a `about:` option to render any string starting with `/` or `//` as a URL?
