### ISSUE TITLE
Some URLs not being displayed

### ISSUE THREAD

**Issue by Blargel** [bhollis/jsonview#50]
What I expect:
![screenshot 2014-03-20 15 03 27](https://f.cloud.github.com/assets/126631/2478224/a09c07e6-b07b-11e3-91c1-de371ad74967.png)

What I get:
![screenshot 2014-03-20 15 03 12](https://f.cloud.github.com/assets/126631/2478226/b56422c6-b07b-11e3-9a10-9cb09934c7ef.png)

Note that it does not even say null. The field just simply doesn't say anything. I'm not sure what causes this to happen, but you can see that the url is not being displayed correctly, possibly because it's oddly constructed. The strange thing is that if I save the raw JSON to file and open that in Firefox, it'll show the links correctly, which is how I got the first screenshot. A fellow coworker of mine suggested that an invisible character might be messing it up somehow.

Oh right, here are the http headers when I curl the server, since that might matter:
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Content-Type: application/json;charset=UTF-8
< Content-Length: 2711
< Date: Thu, 20 Mar 2014 22:18:09 GMT

Unfortunately, I don't think I can give the entire JSON body I receive since it might contain data that I'm not actually allowed to share.

**Comment by bhollis** [comment]
I'm unable to reproduce this in JSONView 0.9 with the information given. My guess is that there's some sort of unprintable character messing with things, but without the original source I don't know what it could be.
