### ISSUE TITLE
Make the newline char visible

### ISSUE THREAD

**Issue by wangyi6854** [bhollis/jsonview#53]
Hello,

I found the '\n\r' char displayed directly instead of replacing by '<br />'. Could you make this replacement happened, or add an option to it?

Thanks!

**Comment by TrangPham** [comment]
@wangyi6854 `\n\r` is not a common newline character set, I believe you mean `\r\n`?

**Comment by bhollis** [comment]
I'm closing this - I prefer having newlines escaped, as they would appear in the actual JSON.
