### ISSUE TITLE
Interupts download of large JSON files, declares them malformed.

### ISSUE THREAD

**Issue by hwine** [bhollis/jsonview#54]
At least with FF 28 and later, the extension appears to interfere with the download of large JSON files, and then declare the truncated file malformed. When the extension is disabled, the full json file downloads correctly.
The truncation is shown both in the window display, and in the "Page Info" dialog, where the size will vary, but be much shorter than the actual file. E.g. 100K or 200K from a 10M file.
Sample URL to replicate: http://people.mozilla.org/~hwine/tmp/allthethings.json

**Comment by Cosafina** [comment]
I don't know if it's any help to you at all, but the link to people.mozilla.org that hwine provided won't load at all with Firefox 35.0.1 and JSONView 0.9.  It loads fine in Chrome, but Firefox won't play ball.
This also means we can't use it on our own application.  Are there any plans to get this fixed?

**Comment by bhollis** [comment]
I'm able to reproduce this with @oliver-graetz's code (infinite spinner) with JSONView 0.9.1 on Firefox 38. I'm *not* able to reproduce it with the unreleased JSONView 1.0 (which hasn't changed anything about this) on Firefox Nightly (41). So I guess we just have to wait for Firefox to improve.
