### ISSUE TITLE
jsonview modifies response in iframe

### ISSUE THREAD

**Issue by perungrad** [bhollis/jsonview#76]
Hello,
I have a page with the iframe window for ajax file uploads. After an upload server responds with json object. I try to read contents of the iframe window with jquery method `$(iframeElemSelector).contents().text()`

If the JsonView addon is enabled, result of this call contains absolute url of the current page prepend to the string. When this addon is disabled, no url is prepend to the string.

I am using slightly [modified version of jquery.ajaxfileupload](https://github.com/perungrad/jQuery.AjaxFileUpload.js) library for handling upload.

**Comment by bhollis** [comment]
I'm afraid I have no idea how to prevent it from doing that.
