### ISSUE TITLE
dark theme?

### ISSUE THREAD

**Issue by ryenus** [bhollis/jsonview#87]
Possible to add a [Monokai like dark theme][2], just like the [JSON Viewer for Chrome][1]?

[1]: https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh
[2]: http://www.monokai.nl/blog/2006/07/15/textmate-color-theme/

**Comment by Cordazar** [comment]
There seems to be a light and a dark theme implemented but with no discernable way to toggle them except for editing the class-name via dev tools.
Is there a way to change theme that I don't know about or is it planned for the future?

**Comment by bhollis** [comment]
There are not light and dark themes implemented, nor will there be.

**Comment by Cordazar** [comment]
I'm very sorry. I missed that Firefox DevEd 44.02a had included their own json viewer.. which comes with two themes apparently and also takes precedence over installed addons.

**Comment by SeriousM** [comment]
I know, this is a very old post but I just want to add some information:

To enable the json viewer in firefox stable you need to set the setting `devtools.jsonview.enabled` to true in the about:config.
https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer
