### ISSUE TITLE
JSONView not working with vimperator

### ISSUE THREAD

**Issue by hemantborole** [bhollis/jsonview#92]
Hi
I think this was definitely working at some point, however, with firefox and vimperator on archlinux, I have started to notice that the json is not rendering as json, but plain text. Sometimes, it even opens the save as dialog. the example file in the readme here, opens the "open with" dialog box.
The same plugin works fine in chromium.

**Comment by bhollis** [comment]
The Chrome extension is a totally different project, and is implemented in a different way.

It sounds to me like Vimperator is interfering with JSONView, not the other way around - if anyone wants to submit a pull request that fixes it I'd be happy to accept, though.

**Comment by bhollis** [comment]
I'm closing this, but I'd be happy to look at a pull request that makes JSONView work better with vimperator.
