### ISSUE TITLE
Raw github urls containing json are not getting rendered.

### ISSUE THREAD

**Issue by prat0318** [bhollis/jsonview#93]
I guess it was working before and stopped working recently. Json files in [raw github](https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore-simple.json) are shown as simple text instead of beautiful rendering. Tried in FF 35, 36.

Awesome plugin though :+1: .

**Comment by prat0318** [comment]
May be, because the respone `content-type` turns out to be:
```
Content-Type: text/plain; charset=utf-8
```
instead of `application/json; charset=utf-8`. The second check of checking the url and guessing that it is a json file would be very helpful. (Chrome JSONView 0.0.32.2 renders the above github link just fine).

**Comment by bhollis** [comment]
Sorry, JSONView won't be modified to override the stated content type the content is served as by guessing based on the URL.
