### ISSUE TITLE
URL should also have quotes to allow copy-pasting of JSON

### ISSUE THREAD

**Issue by Darker** [bhollis/jsonview#94]
I'm really happy for finding this JSON viewer. It has one flaw though that regularly causes problems: URLs in their link form no longer have quotes. This is invalid and when I copy JSON I need to add the quotes manually.

Why could not URL have quotes and color as string node, but have an underline and be clickable? That would be much less confusing.

**Comment by jerone** [comment]
Actually the quotes `&quot;` [are around the links](https://github.com/bhollis/jsonview/blob/master/lib/jsonformatter.js#L64), but they are [hidden from view](https://github.com/bhollis/jsonview/blob/master/data/default.css#L64-L68). However when you select the JSON, those quotes around the url and around all keys _are_ being copied.

**Comment by bhollis** [comment]
Yup, give copy-pasting a try - the quotes will magically appear in the pasted text!

**Comment by Darker** [comment]
I tried it, but I probably did something wrong (or something was wrong with the JSON). Thanks for clearing it up, it's really a nice solution!
