### ISSUE TITLE
Long numbers truncated

### ISSUE THREAD

**Issue by sebastien** [bhollis/jsonview#95]
The following JSON 

```json
{"id":4836529614990000617}
```

is displayed as 

```
{"id": 4836529614990000000}
```
If you change the number to `4836529614991234567891` it will be displayed as `4.836529614991234e+21`.

Maybe it's a printf option that should be something else than `%d`?
![screenshot from 2015-04-29 16 13 54](https://cloud.githubusercontent.com/assets/14598/7400429/e58b607e-ee8a-11e4-9464-f8e4d4e1cfee.png)

**Comment by bhollis** [comment]
Here's the explanation: https://github.com/bhollis/jsonview/issues/21
