### ISSUE TITLE
Ellipsis for collapsed object/array not visible

### ISSUE THREAD

**Issue by stanio** [bhollis/jsonview#96]
Not sure if limited to:
```
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:39.0) Gecko/20100101 Firefox/39.0
```
on a high 192 dpi screen.

The ellipsis character replacing the content of collapsed objects/arrays doesn't appear visible:

![collapsed1-bad](https://cloud.githubusercontent.com/assets/1247730/7445984/f26b4bf8-f1d0-11e4-802b-4e3c90ca6618.png)

![collapsed2-bad](https://cloud.githubusercontent.com/assets/1247730/7445985/017e01e4-f1d1-11e4-9cdf-b922d421c42a.png)

As far as I've identified, appears related to the combination of the following style declarations used:

```css
.collapsible.collapsed {
  height: .8em;
  overflow: hidden;
}
```

Changing it as `height: 1em` (using Web developer tools) appears to correct the display:

![collapsed1-ok](https://cloud.githubusercontent.com/assets/1247730/7446010/eeb09562-f1d1-11e4-9233-f8d17c49a8a4.png)

![collapsed2-ok](https://cloud.githubusercontent.com/assets/1247730/7446011/f3219b0a-f1d1-11e4-828d-fda8a6c09a2d.png)

**Comment by bhollis** [comment]
Thanks for the report. This was already fixed in #83 but hasn't been released yet.
